### ISSUE TITLE
feature request: support pg_query_scan, pg_query_split, pg_query_split_with_scanner

### ISSUE THREAD

**Issue by SKalt** [pganalyze/pg_query.rs#5]
All of which are published in [pg_query.h](https://github.com/pganalyze/libpg_query/blob/13-latest/pg_query.h#L77).

I've got a viable draft of these functions over at [skalt/pg_query_wrapper](https://github.com/SKalt/pg_query_wrapper/blob/master/src/lib.rs#L252), and I'd be happy to adapt and PR them to this repo.

**Comment by seanlinsley** [comment]
@SKalt great, feel free to submit a PR and we'll review it when we're able to
