### ISSUE TITLE
Please update the crate

### ISSUE THREAD

**Issue by rex-remind101** [pganalyze/pg_query.rs#9]
The crate https://crates.io/crates/pg_query is still pointing at what is presumably an old repo and not the latest version. Please update it.

**Comment by rex-remind101** [comment]
>pg_query = "^0.7"` candidate versions found which didn't match: 0.6.0, 0.5.0, 0.4.0,

**Comment by rex-remind101** [comment]
@seanlinsley ?

**Comment by lfittl** [comment]
@rex-remind101 Thanks for pointing this out - we're looking into it.

**Comment by seanlinsley** [comment]
we've just published 0.7.0 on crates.io
